name: Staff onboarding
description: Add a new staff member to Flow!
title: "[New staff]: "
assignees:
  - chadsoo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: full_name
    attributes:
      label: Full name
      placeholder: ex. Joe Soap
    validations:
      required: false
  - type: input
    id: email
    attributes:
      label: Personal email address
      placeholder: ex. example@example.com
    validations:
      required: true
  - type: input
    id: mobile_number
    attributes:
      label: Mobile number
      placeholder: ex. 27 83 393 3333
    validations:
      required: false   
  - type: input
    id: address
    attributes:
      label: Address 
      placeholder: ex. 884 Main Rd, Rosebank, Johannesburg
    validations:
      required: false         
  - type: input
    id: software_requirements
    attributes:
      label: Special software requirements 
      placeholder: ex. Creative Cloud, Invision
    validations:
      required: false           
  - type: input
    id: contracted_number_of_hours
    attributes:
      label: Contracted no. of hours per week
      placeholder: ex. 40
    validations:
      required: false           
  - type: input
    id: hdi_status
    attributes:
      label: HDI Status
      placeholder: ex. Black male, white female etc
    validations:
      required: false         
  - type: input
    id: date_of_birth
    attributes:
      label: Date of Birth
      placeholder: ex. 6 June 1983
    validations:
      required: false        
  - type: input
    id: team
    attributes:
      label: Team
      placeholder: ex. Design
    validations:
      required: false  
  - type: input
    id: employment_starts
    attributes:
      label: Employment start date 
      placeholder: ex. 1 Jan 2022
    validations:
      required: false    
  - type: checkboxes
    id: checks-completed
    attributes:
      label: What steps have been completed (these will be ticked by IT later)
      options:
        - label: Flow machine registered on IT registry under staff member name and insured (if new)
        - label: Flow hardware acceptance form received
        - label: Acceptance of IT policy form received
        - label: Gsuite account created
        - label: Gsuite two factor enabled (https://myaccount.google.com/security)
        - label: Gsuite personal profile and picture set (https://myaccount.google.com/profile)
        - label: Last Pass account created
        - label: Creative Suite account created (if required)
        - label: Github account created
        - label: Timesponge account created
        - label: Timesponge capacity set
        - label: Added to Flow staff group and daily staff meeting
        - label: Google Docs training and onboarding completed
        - label: Google Mail and Chat training and onboarding completed
        - label: Google Meet training completed
        - label: LastPass training and onboarding completed
        - label: Github training and onboarding completed
