name: Staff onboarding
description: Add a new staff member to Flow!
title: "[New staff]: "
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: full_name
    attributes:
      label: Full name
      placeholder: ex. Joe Soap
    validations:
      required: false
  - type: input
    id: email
    attributes:
      label: Personal email address
      placeholder: ex. example@example.com
    validations:
      required: false
  - type: input
    id: mobile_number
    attributes:
      label: Mobile number
      placeholder: ex. 27 83 393 3333
    validations:
      required: false   
  - type: input
    id: address
    attributes:
      label: Address 
      placeholder: ex. 884 Main Rd, Rosebank, Johannesburg
    validations:
      required: false         
  - type: input
    id: software_requirements
    attributes:
      label: Special software requirements 
      placeholder: ex. Creative Cloud, Invision
    validations:
      required: false           
  - type: input
    id: contracted_number_of_hours
    attributes:
      label: Contracted no. of hours per week
      placeholder: ex. 40
    validations:
      required: false           
  - type: input
    id: hdi_status
    attributes:
      label: HDI Status
      placeholder: ex. Black male, white female etc
    validations:
      required: false         
  - type: input
    id: date_of_birth
    attributes:
      label: HDI Status
      placeholder: ex. 6 June 1983
    validations:
      required: false        
  - type: input
    id: team
    attributes:
      label: Team
      placeholder: ex. Design
    validations:
      required: false  
  - type: input
    id: employment_starts
    attributes:
      label: Employment start date 
      placeholder: ex. 1 Jan 2022
    validations:
      required: false        
   
